### ISSUE TITLE
Error when installing on Python 

### ISSUE THREAD

**Issue by lplanqua** [mpi4py/mpi4py#351]
Hi, 
I'm trying to install mpi4py with pip on my Linux machine but the installation fails.  I'm working with Python 3.11, I've checked that mpiexec is in my PATH but I get the following error message. 

Here are the last lines printed on the terminal (and attached the full error message). 
Have you any idea what is the cause of this problem ?

` building 'mpi4py.dl' extension
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DHAVE_DLFCN_H=1 -DHAVE_DLOPEN=1 -I/usr/include/python3.11 -c src/dynload.c -o build/temp.linux-x86_64-cpython-311/src/dynload.o
      src/dynload.c:5:10: fatal error: Python.h: No such file or directory
          5 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      warning: build_ext: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

      warning: build_ext: building optional extension "mpi4py.dl" failed

      checking for MPI compile and link ...
      /usr/bin/mpicc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.11 -c _configtest.c -o _configtest.o
      _configtest.c:2:10: fatal error: mpi.h: No such file or directory
          2 | #include <mpi.h>
            |          ^~~~~~~
      compilation terminated.
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot compile MPI programs. Check your configuration!!!
      [end of output]`

`
[log.log](https://github.com/mpi4py/mpi4py/files/11351336/log.log)
`

**Comment by dalcinl** [comment]
Looks like you have to install the Python and MPI development packages with your system package manager, for example, `sudo apt install python-dev` and similarly or the `libopenmpi-dev` assuming you are using Open MPI on a Debian or Ubuntu derivative.

**Comment by Liaukx** [comment]
I am using Nvidia HPCX openmpi  in my system. I run the command "which mpicc"，the system can return the correct result.  But I got the same error, what should I do ?

**Comment by dalcinl** [comment]
@Liaukx Which error? The one about `#include "Python.h"`? What Linux distribution are you using? You have to provide complete information about your development environment, otherwise how can I guess what you guys are using? The minimum information you should provide is the following:

* Linux distro and its version
* the output of `which python`
* the output of `python --version`
* the output of `ompi_info --version`
* the output of `which mpicc`
* the output of `mpicc -show`
* The full output of `pip install -vvv mpi4py` attached as a file, so that I can see the actual failure.
